/*
HDL Orders — HDLQ, HDLLQ, NHDLQ

Purpose: Pull order and demographic detail for HDL-related tests.

Parameters:
  :START_DATE - Start of date range in YYYYMMDD format (e.g., 20250101)
  :END_DATE   - End of date range in YYYYMMDD format (e.g., 20251231)
*/

SELECT
  p.ID                AS MRN,
  p.LAST_NAME,
  p.FIRST_NAME,
  p.DOB_DT            AS DATE_OF_BIRTH,
  p.SEX,
  o.ID                AS ORDER_ID,
  tr.GROUP_TEST_ID    AS ORDERED_TEST,
  tr.TEST_ID          AS COMPONENT_TEST,
  ot.CLINIC_ID        AS ORDERING_CLINIC,
  ot.DOCTOR_ID        AS ORDERING_DOCTOR,
  tr.TESTING_WORKSTATION_ID  AS TESTING_WORKSTATION,
  tr.TEST_PERFORMING_LOCATION AS PERFORMING_LOCATION,
  tr.RESULT,
  tr.UNITS,
  tr.STATE            AS RESULT_STATE,
  TO_CHAR(ot.ORDERING_DT, 'YYYYMMDD HH24:MI:SS')  AS ORDERED_DT,
  TO_CHAR(tr.COLLECT_DT, 'YYYYMMDD HH24:MI:SS')    AS COLLECTED_DT,
  TO_CHAR(tr.RECEIVE_DT, 'YYYYMMDD HH24:MI:SS')    AS RECEIVED_DT,
  TO_CHAR(tr.VERIFIED_DT, 'YYYYMMDD HH24:MI:SS')   AS VERIFIED_DT
FROM V_P_LAB_TEST_RESULT tr
JOIN V_P_LAB_ORDER o ON o.AA_ID = tr.ORDER_AA_ID
JOIN V_P_LAB_STAY s ON s.AA_ID = o.STAY_AA_ID
JOIN V_P_LAB_PATIENT p ON p.AA_ID = s.PATIENT_AA_ID
JOIN V_P_LAB_ORDERED_TEST ot ON ot.ORDER_AA_ID = tr.ORDER_AA_ID
                             AND ot.TEST_ID = tr.GROUP_TEST_ID
                             AND ot.WORKSTATION_ID = tr.ORDERING_WORKSTATION_ID
WHERE tr.TEST_ID IN ('HDLQ', 'NHDLQ')
  AND tr.STATE IN ('Final', 'Corrected')
  AND TRUNC(ot.ORDERING_DT) BETWEEN TO_DATE(:START_DATE, 'YYYYMMDD')
                                 AND TO_DATE(:END_DATE, 'YYYYMMDD')
ORDER BY ot.ORDERING_DT DESC;
