/*
Quick lookup: All orders for OLIGX in the last 6 months
*/

SELECT
  o.ID AS ORDER_ID,
  p.ID AS MRN,
  p.LAST_NAME,
  p.FIRST_NAME,
  ot.TEST_ID,
  ot.WORKSTATION_ID,
  ot.CLINIC_ID,
  TO_CHAR(ot.ORDERING_DT, 'YYYY-MM-DD HH24:MI') AS ORDERING_DT,
  ot.PRIORITY,
  ot.CANCELLED_FLAG
FROM V_P_LAB_ORDERED_TEST ot
JOIN V_P_LAB_ORDER o ON o.AA_ID = ot.ORDER_AA_ID
JOIN V_P_LAB_STAY s ON s.AA_ID = o.STAY_AA_ID
JOIN V_P_LAB_PATIENT p ON p.AA_ID = s.PATIENT_AA_ID
WHERE ot.TEST_ID = 'OLIGX'
  AND ot.ORDERING_DT >= ADD_MONTHS(SYSDATE, -6)
  AND REGEXP_LIKE(p.ID, '^E[0-9]+$')
ORDER BY ot.ORDERING_DT DESC;
