SELECT ord.ID AS ORDERNUM,
  Concat(Concat(pt.LAST_NAME, ','), pt.FIRST_NAME) AS PTNAME,
  ord.TESTS_CANCEL AS CANC,
  To_Char(tr.COLLECT_DT, 'YYYYMMDD') AS COLL_DATE,
  tr.COLLECT_DT AS TR_COLL_DT,
  tr.RECEIVE_DT AS TR_REC_DT,
  tr.VERIFIED_FLAG AS VERFLAG,
  ord.PRIORITY AS PRIORITY,
  (CASE
    WHEN (tr.VERIFIED_FLAG) = 'N' THEN 'Not Verified'
    WHEN (tr.VERIFIED_FLAG) = 'Y' THEN 'Verified'
  END) AS VER,
  tr.GROUP_TEST_ID AS G_TEST,
  tr.SPEC_RECEIVED,
  tr.ORDERING_WORKSTATION_ID AS WRKST
FROM (
  SELECT DISTINCT
    ORDER_AA_ID,
    GROUP_TEST_ID,
    COLLECT_DT,
    RECEIVE_DT,
    VERIFIED_FLAG,
    SPEC_RECEIVED,
    ORDERING_WORKSTATION_ID
  FROM V_P_LAB_TEST_RESULT
  WHERE COLLECT_DT >= TO_DATE(:Date1, 'YYYYMMDD')
    AND COLLECT_DT <  TO_DATE(:Date2, 'YYYYMMDD') + 1
    AND VERIFIED_FLAG = 'N'
    AND SPEC_RECEIVED = 'Y'
    AND ORDERING_WORKSTATION_ID = 'TCHA'
) tr
INNER JOIN V_P_LAB_ORDER ord  ON tr.ORDER_AA_ID = ord.AA_ID
INNER JOIN V_P_LAB_STAY st     ON ord.STAY_AA_ID = st.AA_ID
INNER JOIN V_P_LAB_PATIENT pt  ON st.PATIENT_AA_ID = pt.AA_ID
ORDER BY ORDERNUM,
  PTNAME
