SELECT
    o.ID AS order_no,
    p.ID AS mrn,
    p.LAST_NAME,
    p.FIRST_NAME,
    ot.TEST_ID,
    ot.WORKSTATION_ID,
    tr.STATE AS result_state,
    o.ORDERED_DT,
    tr.COLLECT_DT,
    tr.RECEIVE_DT,
    tr.TEST_DT,
    tr.VERIFIED_DT,
    tr.TESTING_WORKSTATION_ID
FROM V_P_LAB_ORDERED_TEST ot
JOIN V_P_LAB_ORDER o ON o.AA_ID = ot.ORDER_AA_ID
JOIN V_P_LAB_STAY s ON s.AA_ID = o.STAY_AA_ID
JOIN V_P_LAB_PATIENT p ON p.AA_ID = s.PATIENT_AA_ID
LEFT JOIN V_P_LAB_TEST_RESULT tr
    ON tr.ORDER_AA_ID = ot.ORDER_AA_ID
    AND tr.GROUP_TEST_ID = ot.TEST_ID
    AND tr.ORDERING_WORKSTATION_ID = ot.WORKSTATION_ID
WHERE ot.TEST_ID IN ('CBCWD', 'CBCD')
  AND ot.CANCELLED_FLAG = 0
  AND o.ORDERED_DT >= TO_DATE(:start_date, 'YYYYMMDD')
  AND o.ORDERED_DT <  TO_DATE(:end_date, 'YYYYMMDD')
ORDER BY o.ORDERED_DT;
    