SELECT DISTINCT ELR_Test.PTNAME AS PTNAME,
  ELR_Test.MRN AS MRN,
  Max(ELR_Test.ORDNUM) AS ORDNUM,
  Max(ELR_Test.RECDT) AS RECDT,
  Max(ELR_Test.VERDT) AS VERDT,
  Max(ELR_Test.TESTID) AS TESTID,
  ELR_Test.TESTNAME AS TESTNAME,
  ELR_Test.RESULT AS RESULT,
  Max(ELR_Test.COLLDT) AS COLLDT,
  Max(ELR_Test.RECDATE) AS RECDATE,
  Max(ELR_Test.TCRECDATE) AS TCRECDATE,
  ELR_Test.DEPOT AS DEPOT,
  ELR_Test.SITE AS SITE,
  ELR_Test.EDATE AS EDATE,
  ELR_Test.SDATE AS SDATE
FROM (SELECT DISTINCT AU.PTNAME AS PTNAME,
    AU.MRN AS MRN,
    Max(AU.ORDNUM) AS ORDNUM,
    Max(AU.COLLDT) AS COLLDT,
    Max(AU.RECDT) AS RECDT,
    Max(AU.RECDATE) AS RECDATE,
    Max(AU.TCRECDATE) AS TCRECDATE,
    Max(AU.VERDT) AS VERDT,
    AU.TESTID AS TESTID,
    AU.TESTNAME AS TESTNAME,
    AU.RESULT AS RESULT,
    AU.ORDERED_DATE AS ORDERED_DATE,
    AU.DEPOT AS DEPOT,
    AU.SITE AS SITE,
    AU.SDATE AS SDATE,
    AU.EDATE AS EDATE
  FROM (SELECT Concat(Concat(pt.LAST_NAME, ','), pt.FIRST_NAME) AS PTNAME,
      pt.ID AS MRN,
      o.ID AS ORDNUM,
      otst.COLLECTED_DT AS COLLDT,
      otst.RECEIVED_DT AS RECDT,
      otst.RECEIVED_DATE AS RECDATE,
      To_Char(otst.RECEIVED_DT, 'YYYYMMDD') AS TCRECDATE,
      tr.VERIFIED_DT AS VERDT,
      tr.TEST_ID AS TESTID,
      tr.TEST_NAME AS TESTNAME,
      tr.RESULT AS RESULT,
      o.ORDERED_DATE AS ORDERED_DATE,
      o.COLLECT_CENTER_ID AS DEPOT,
      Decode(o.COLLECT_CENTER_ID, 'J%', 'JNS') AS SITE,
      To_Char(Trunc(Last_Day(Add_Months(SYSDATE, -:Month_1))) + (23 / 24),
      'MM/DD/YYYY') AS SDATE,
      To_Char(Trunc(Last_Day(Add_Months(SYSDATE, -:Month_2))) + (23 / 24),
      'MM/DD/YYYY') AS EDATE
    FROM V_P_LAB_PATIENT pt
      INNER JOIN V_P_LAB_STAY st ON st.PATIENT_AA_ID = pt.AA_ID
      INNER JOIN V_P_LAB_ORDER o ON o.STAY_AA_ID = st.AA_ID
      INNER JOIN V_P_LAB_ORDERED_TEST otst ON otst.ORDER_AA_ID = o.AA_ID
      INNER JOIN V_P_LAB_TEST_RESULT tr ON tr.ORDER_AA_ID = o.AA_ID
    WHERE otst.COLLECTED_DT IS NOT NULL AND otst.RECEIVED_DT BETWEEN
      Trunc(Last_Day(Add_Months(SYSDATE, -:Month_1))) + (23 / 24) AND
      Trunc(Last_Day(Add_Months(SYSDATE, -:Month_2))) + (23 / 24) AND
      tr.TEST_ID IN ('CRPTI', 'CRPTR', 'CRYBR', 'CRYCR', 'CTMA3', 'CTMA4',
      'CTMAC', 'CTMAR', 'FLAR2', 'FLAR3', 'FLAR4', 'FLUAR', 'FLUB2', 'FLUB3',
      'FLUB4', 'FLUBR', 'GCMA3', 'GCMA4', 'GCMAC', 'GCMAR', 'HAVAR', 'HAVMR',
      'HBCMR', 'HBSAR', 'HBSNR', 'HBSQR', 'HCVPR', 'HCVR', 'HCVRR', 'HHS1R',
      'HHS2R', 'HI12R', 'HIVCR', 'HIVPR', 'HIVRC', 'HIVSR', 'HP24R', 'INFA2',
      'INFA3', 'INFA4', 'INFA5', 'INFA6', 'INFAR', 'INFAR', 'INFB2', 'INFB3',
      'INFB4', 'INFB5', 'INFB6', 'INFBR', 'INFBR', 'INH1A', 'INH1B', 'INH1C',
      'INH1D', 'INH1E', 'INH1R', 'INH3A', 'INH3B', 'INH3C', 'INH3D', 'INH3E',
      'INH3R', 'INHBR', 'LYDMR', 'LYGGR', 'LYGMR', 'LYGR', 'LYMER', 'MVAMR',
      'RCRYR', 'RGAR', 'RPRR', 'RPRT', 'RSVA2', 'RSVA3', 'RSVA4', 'RSVA5',
      'RSVA6', 'RSVAR', 'RSVB2', 'RSVB3', 'RSVB4', 'RSVB5', 'RSVB6', 'RSVBR',
      'RSVR', 'RSVR1', 'RSVR2', 'SHI1R', 'SHI2R', 'SYPHR', 'TOXMR', 'TPPAR',
      'ULAGR') AND NOT tr.RESULT = '.' AND o.COLLECT_CENTER_ID LIKE 'J%') AU
  GROUP BY AU.PTNAME,
    AU.MRN,
    AU.TESTID,
    AU.TESTNAME,
    AU.RESULT,
    AU.ORDERED_DATE,
    AU.DEPOT,
    AU.SITE,
    AU.SDATE,
    AU.EDATE
  HAVING Max(AU.COLLDT) IS NOT NULL AND
    Max(AU.RECDT) BETWEEN Trunc(Last_Day(Add_Months(SYSDATE, -:Month_1))) +
    (23 / 24) AND Trunc(Last_Day(Add_Months(SYSDATE, -:Month_2))) + (23 / 24)
  ORDER BY ORDNUM) ELR_Test
GROUP BY ELR_Test.PTNAME,
  ELR_Test.MRN,
  ELR_Test.TESTNAME,
  ELR_Test.RESULT,
  ELR_Test.DEPOT,
  ELR_Test.SITE,
  ELR_Test.EDATE,
  ELR_Test.SDATE
ORDER BY ORDNUM,
  TESTID