SELECT
    CONCAT(CONCAT(tubeinfo.LAST_NAME, ', '), tubeinfo.FIRST_NAME) AS PATIENT,
    tubeinfo.MRN,
    ord.ID AS ORD_NUM,
    sb.CODE AS BARCODE,
    tubeinfo.COLLECTION_PHLEB,
    tr.GROUP_TEST_ID,
    tr.TEST_ID,
    tr.RESULT,
    tr.STATE,
    tr.TESTING_WORKSTATION_ID,
    TO_CHAR(tubeinfo.COLLECTION_DT, 'MM/DD/YYYY HH24:MI') AS COL_DT,
    TO_CHAR(tr.RECEIVE_DT, 'MM/DD/YYYY HH24:MI') AS REC_DT,
    TO_CHAR(tr.TEST_DT, 'MM/DD/YYYY HH24:MI') AS TEST_DT,
    TO_CHAR(tr.VERIFIED_DT, 'MM/DD/YYYY HH24:MI') AS VERIFIED_DT,
    ord.COLLECT_CENTER_ID AS DEPOT,
    ord.ORDERING_CLINIC_ID AS ORDWARD,
    stay.CLINIC_ID AS PTWARD
FROM V_P_LAB_TEST_RESULT tr
JOIN V_P_LAB_TEST_TO_TUBE ttt ON ttt.RESULT_AA_ID = tr.AA_ID
JOIN V_P_LAB_SPECIMEN_BARCODE sb ON sb.TUBE_AA_ID = ttt.TUBE_AA_ID
    AND sb.CODE_TYPE = 'B'
JOIN V_P_LAB_ORDER ord ON ord.ID = sb.ORDER_ID
JOIN V_P_LAB_STAY stay ON stay.AA_ID = ord.STAY_AA_ID
JOIN V_P_LAB_TUBEINFO tubeinfo ON tubeinfo.ORDER_ID = ord.ID
    AND tubeinfo.TUBE_TYPE = tr.SPECIMEN_TYPE
WHERE tr.GROUP_TEST_ID IN ('SOFIA', 'SOFII')
  AND tr.TEST_ID IN ('SOFSO', 'SOFSI')
  AND tr.STATE <> 'Canceled'
  AND tubeinfo.COLLECTION_DT >= TO_DATE(:start_date, 'YYYYMMDD')
  AND tubeinfo.COLLECTION_DT < TO_DATE(:end_date, 'YYYYMMDD')
ORDER BY tubeinfo.COLLECTION_DT DESC