-- DIAGNOSTIC 1: Find candidate test codes by name (CD4, HIV)
SELECT ID, NAME, ACTIVE, DEPARTMENT_ID, WORKSTATION_ID
FROM V_S_LAB_TEST
WHERE UPPER(NAME) LIKE '%CD4%'
   OR UPPER(NAME) LIKE '%HIV%'
ORDER BY NAME;

-- DIAGNOSTIC 2: Count results in the date window by TEST_ID + PERF_DEPT
-- (no TEST_ID/dept filter, no TEST_ID=GROUP_TEST_ID filter) so we can see what exists.
SELECT
    tr.TEST_ID,
    tr.GROUP_TEST_ID,
    tr.TEST_PERFORMING_DEPT,
    tr.STATE,
    COUNT(*) AS CNT
FROM V_P_LAB_TEST_RESULT tr
WHERE tr.VERIFIED_DT BETWEEN TO_DATE('2026-01-01','YYYY-MM-DD')
                         AND TO_DATE('2026-04-14','YYYY-MM-DD')
  AND (UPPER(tr.TEST_ID) LIKE '%CD4%' OR UPPER(tr.TEST_ID) LIKE '%HIV%'
       OR UPPER(tr.GROUP_TEST_ID) LIKE '%CD4%' OR UPPER(tr.GROUP_TEST_ID) LIKE '%HIV%')
GROUP BY tr.TEST_ID, tr.GROUP_TEST_ID, tr.TEST_PERFORMING_DEPT, tr.STATE
ORDER BY CNT DESC;

-- DIAGNOSTIC 3: Relax the main query one filter at a time.
-- Run these counts and see where rows drop to 0.
SELECT 'A: just date + state' AS step, COUNT(*) AS n
FROM V_P_LAB_TEST_RESULT tr
JOIN V_P_LAB_ORDER o ON o.AA_ID = tr.ORDER_AA_ID
LEFT JOIN V_P_LAB_TUBE tu ON tu.ORDER_AA_ID = o.AA_ID
LEFT JOIN V_P_LAB_SPECIMEN sp ON sp.AA_ID = tu.SPECIMEN_AA_ID
WHERE tr.STATE IN ('Final','Verified','Corrected')
  AND sp.COLLECTION_DT BETWEEN TO_DATE('2026-01-01','YYYY-MM-DD') AND TO_DATE('2026-04-14','YYYY-MM-DD')
  AND tr.TEST_ID IN ('CD4P','CD4A','HIVPC','HIVGN')
UNION ALL
SELECT 'B: + TEST_ID=GROUP_TEST_ID', COUNT(*)
FROM V_P_LAB_TEST_RESULT tr
JOIN V_P_LAB_ORDER o ON o.AA_ID = tr.ORDER_AA_ID
LEFT JOIN V_P_LAB_TUBE tu ON tu.ORDER_AA_ID = o.AA_ID
LEFT JOIN V_P_LAB_SPECIMEN sp ON sp.AA_ID = tu.SPECIMEN_AA_ID
WHERE tr.STATE IN ('Final','Verified','Corrected')
  AND sp.COLLECTION_DT BETWEEN TO_DATE('2026-01-01','YYYY-MM-DD') AND TO_DATE('2026-04-14','YYYY-MM-DD')
  AND tr.TEST_ID IN ('CD4P','CD4A','HIVPC','HIVGN')
  AND tr.TEST_ID = tr.GROUP_TEST_ID
UNION ALL
SELECT 'C: + dept filters', COUNT(*)
FROM V_P_LAB_TEST_RESULT tr
JOIN V_P_LAB_ORDER o ON o.AA_ID = tr.ORDER_AA_ID
LEFT JOIN V_P_LAB_TUBE tu ON tu.ORDER_AA_ID = o.AA_ID
LEFT JOIN V_P_LAB_SPECIMEN sp ON sp.AA_ID = tu.SPECIMEN_AA_ID
WHERE tr.STATE IN ('Final','Verified','Corrected')
  AND sp.COLLECTION_DT BETWEEN TO_DATE('2026-01-01','YYYY-MM-DD') AND TO_DATE('2026-04-14','YYYY-MM-DD')
  AND tr.TEST_ID = tr.GROUP_TEST_ID
  AND (
        (tr.TEST_ID IN ('CD4P','CD4A') AND tr.TEST_PERFORMING_DEPT = 'TFLOW')
     OR  tr.TEST_ID = 'HIVPC'
     OR (tr.TEST_ID = 'HIVGN' AND tr.TEST_PERFORMING_DEPT = 'TMOL')
      );
